Repository LemonFace0309/Study-Space, pull requests merged in 2021-08, with the labels that each got.

#123 This fixes 404 errors in prod
  pages/_app.js
  pages/dashboard/index.js
  pages/friends/index.js
  pages/index.js
Labels: bug

#109 fix mobile responsiveness
  components/Dashboard/Modals/ProfileDialog/AccountDetails.js
  components/Dashboard/Modals/ProfileDialog/index.js
  models/Friends.js
  pages/dashboard/index.js
Labels: improvement

#124 104_todo
  components/Spaces/StudySpace/People.js
  components/Spaces/StudySpace/TodoList.js
  components/Spaces/Video/CallOptions.js
  components/Spaces/Video/CallTabPanel.js
  components/Spaces/Video/CallTabs/TabPanelHeader.js
  components/Spaces/Video/CallTabs/index.js
  components/Spaces/Video/LeaveCall.js
  pages/room/[...id].js
Labels: enhancement

#127 125 music functionality
  atoms/client.js
  atoms/spotify.js
  components/Card.js
  components/Middle.js
  components/RightBar.js
  components/Spaces/CallTabs/Chat/Conversation/index.js
  components/Spaces/CallTabs/Chat/index.js
  components/Spaces/CallTabs/Layout/CallTabPanel.js
  components/Spaces/CallTabs/Layout/TabPanelHeader.js
  components/Spaces/CallTabs/Music/Player.js
  components/Spaces/CallTabs/Music/SpotifyProvider.js
  components/Spaces/CallTabs/Music/Tabs/OurPicks.js
  components/Spaces/CallTabs/Music/Tabs/Queue.js
  components/Spaces/CallTabs/Music/Tabs/SearchSongs.js
  components/Spaces/CallTabs/Music/Track.js
  components/Spaces/CallTabs/Music/index.js
  components/Spaces/CallTabs/People.js
  components/Spaces/CallTabs/TodoList.js
  components/Spaces/CallTabs/index.js
  components/Spaces/Music/Tabs/Queue/Song.js
  components/Spaces/Music/Tabs/Queue/index.js
  components/Spaces/Music/Tabs/Youtube.js
  components/Spaces/Music/index.js
  components/Spaces/Video/Notifications.js
  components/Spaces/Video/VideoPlayer.js
  components/Spaces/VideoOptions/CallOptions.js
  components/Spaces/VideoOptions/LeaveCall.js
  package-lock.json
  package.json
  pages/api/spotify/login.js
  pages/api/spotify/refresh-token.js
  pages/room/[...id].js
  pages/room/index.js
  utils/getCookie.js
  utils/renderComponent.js
Labels: enhancement

#118 Add graphql
  components/Dashboard/Cards/SpaceCardModal.js
  components/Dashboard/Modals/ProfileDialog/AccountDetails.js
  components/Dashboard/Modals/ProfileDialog/ChangePassword.js
  components/Dashboard/Modals/ProfileDialog/index.js
  components/Landing/Header/index.js
  context/ConversationProvider.js
  context/SocketProvider.js
  models/NextAuthUser.js
  package-lock.json
  package.json
  pages/_app.js
  pages/api/auth/[...nextauth].js
  pages/api/graphql.js
  pages/api/user/create-new-user.js
  pages/dashboard/index.js
  pages/room/index.js
  utils/apollo/client.js
  utils/apollo/schema/index.js
  utils/apollo/schema/resolvers.js
  utils/apollo/schema/typeDefs.js
Labels: enhancement

#134 131 music tab improvements
  components/Dashboard/Modals/ProfileDialog/AccountDetails.js
  components/Dashboard/Modals/ProfileDialog/ChangePassword.js
  components/Spaces/CallTabs/Music/Player.js
  components/Spaces/CallTabs/Music/Playlist.js
  components/Spaces/CallTabs/Music/SpotifyProvider.js
  components/Spaces/CallTabs/Music/Tabs/Home.js
  components/Spaces/CallTabs/Music/Tabs/OurPicks.js
  components/Spaces/CallTabs/Music/Tabs/Queue.js
  components/Spaces/CallTabs/Music/Tabs/SearchSongs.js
  components/Spaces/CallTabs/Music/Track.js
  components/Spaces/CallTabs/Music/index.js
  pages/api/profile/update-password.js
  pages/api/profile/update-profile.js
  utils/spotify/getClosestImageSize.js
  utils/spotify/parsePlaylists.js
  utils/spotify/parseTracks.js
Labels: improvement

#139 More figma, exiting call, video layouts, video space
  components/Spaces/VideoOptions/CallOptions.js
  components/Spaces/VideoOptions/LeaveCall.js
  components/Spaces/VideoOptions/LeaveCallButton.js
  components/Spaces/VideoOptions/LeaveCallDialog.js
  components/Spaces/VideoOptions/ParticipantsDialog.js
  pages/room/[...id].js
Labels: enhancement

#142 119 continue translations
  components/Auth/AuthDialog.js
  components/Dashboard/Cards/DashboardCard.js
  components/Dashboard/Cards/SpaceCardModal.js
  components/Dashboard/DashboardContainer.js
  components/Dashboard/Modals/ProfileDialog/AccountDetails.js
  components/Dashboard/Modals/ProfileDialog/ChangePassword.js
  components/Dashboard/Modals/ProfileDialog/index.js
  components/Dashboard/Sidebar.js
  components/Landing/Header/NavDrawer.js
  components/Landing/Hero.js
  public/locales/de/common.json
  public/locales/en/common.json
  public/locales/es/common.json
  public/locales/fr/common.json
  public/locales/ja/common.json
  public/locales/ko/common.json
  public/locales/zh/common.json
Labels: improvement

#143 119 continue translations
  components/Dashboard/Cards/SpaceCardModal.js
  components/Dashboard/Modals/ProfileDialog/AccountDetails.js
  components/Landing/Hero.js
  components/Spaces/CallTabs/Music/Tabs/Queue.js
  components/Spaces/CallTabs/Music/Tabs/SearchSongs.js
  components/Spaces/CallTabs/People.js
  components/Spaces/StudySpace/Timer.js
  components/Spaces/VideoOptions/LeaveCallDialog.js
  components/Spaces/VideoOptions/ParticipantsDialog.js
  pages/room/index.js
  public/locales/de/common.json
  public/locales/en/common.json
  public/locales/es/common.json
  public/locales/fr/common.json
  public/locales/ja/common.json
  public/locales/ko/common.json
  public/locales/zh/common.json
Labels: enhancement

#148 144 edit settings functionality
  components/Dashboard/Modals/ProfileDialog/index.js
Labels: improvement

#147 135 fix spotify bugs
  atoms/spotify.js
  components/Spaces/CallTabs/Music/Player.js
  components/Spaces/CallTabs/Music/Playlist.js
  components/Spaces/CallTabs/Music/SpotifyProvider.js
  components/Spaces/CallTabs/Music/SpotifySignUpBlocker.js
  components/Spaces/CallTabs/Music/Tabs/Home.js
  components/Spaces/CallTabs/Music/index.js
  components/Spaces/CallTabs/People.js
  hooks/useLocalStorage.js
  pages/api/spotify/login.js
  pages/room/[...id].js
  pages/room/index.js
  utils/spotify/getClosestImageSize.js
  utils/spotify/parsePlaylists.js
  utils/spotify/parseTracks.js
Labels: bug

#133 128 dynamically load participants into space modal
  components/Dashboard/Cards/SpaceCardModal.js
  components/Dashboard/Cards/SpacePackage.js
  components/Dashboard/DashboardContainer.js
  components/Shared/SpaceCard.js
  models/NextAuthUser.js
  models/Spaces.js
  next.config.js
  package-lock.json
  pages/api/graphql.js
  pages/dashboard/index.js
  pages/room/index.js
  utils/apollo/client.js
  utils/apollo/schema/index.js
  utils/apollo/schema/resolvers.js
  utils/apollo/schema/resolvers/Mutation/index.js
  utils/apollo/schema/resolvers/Query/index.js
  utils/apollo/schema/resolvers/index.js
  utils/apollo/schema/typeDefs.js
  utils/apollo/schema/typedefs/index.js
  utils/apollo/schema/typedefs/schema.graphql
Labels: enhancement

#92 16x speed of this repo with 16x rocket ships
  README.md
Labels: good first issue
