Repository LemonFace0309/Study-Space, pull requests merged in 2021-07, with the labels that each got.

#72 Video call leave, mute, disable video. Call tabs
  components/Spaces/Chat/Conversation/index.js
  components/Spaces/Chat/index.js
  components/Spaces/Video/CallOptions.js
  components/Spaces/Video/CallTabs.js
  components/Spaces/Video/LeaveCall.js
  components/Spaces/Video/Options.js
  pages/room/[...slug].js
  styles/globals.css
Labels: enhancement

#76 76_enahce_client_side_and_server_side_input_validation
  atoms/auth.js
  components/Auth/AuthDialog.js
  components/Dashboard/Modals/ProfileDialog/AccountDetails.js
  components/Dashboard/Modals/ProfileDialog/ChangePassword.js
  components/Dashboard/Modals/ProfileDialog/index.js
  components/Landing/Header/index.js
  components/Spaces/Video/CallOptions.js
  components/Spaces/Video/CallTabs.js
  models/User.js
  package-lock.json
  package.json
  pages/api/create-new-user.js
  pages/api/createnewfriend.js
  pages/api/getuserlist.js
  pages/api/profile/update-image.js
  pages/api/profile/update-password.js
  pages/api/profile/update-profile.js
  pages/auth/index.js
Labels: enhancement

#78 59_join_create_room
  components/Spaces/Chat/index.js
  components/Spaces/StudySpace/People.js
  components/Spaces/Video/CallOptions.js
  components/Spaces/Video/CallTabs.js
  pages/room/[...slug].js
  pages/room/index.js
Labels: enhancement

#83 Messaging abstraced to socket for random usernames
  components/Spaces/Chat/Conversation/index.js
  components/Spaces/Chat/index.js
  components/Spaces/StudySpace/People.js
  components/Spaces/Video/CallTabs.js
  pages/room/[...id].js
Labels: bug, enhancement

#86 85 update dp change
  components/Dashboard/Modals/ProfileDialog/AccountDetails.js
  pages/api/profile/update-image.js
Labels: enhancement

#82 Feature/74/make sidebar collapsible
  components/Dashboard/Cards/DashboardCard.js
  components/Dashboard/Cards/FriendCard.js
  components/Dashboard/Cards/SpacePackage.js
  components/Dashboard/CollapsableDrawer.js
  components/Dashboard/DashboardContainer.js
  components/Dashboard/Sidebar.js
  components/Landing/Header/NavDrawer.js
  pages/dashboard/index.js
  tailwind.config.js
Labels: improvement

#93 Style dashboard cards
  components/Dashboard/Cards/ChartCard.js
  components/Dashboard/Cards/DashboardCard.js
  components/Dashboard/Cards/FriendCard.js
  components/Dashboard/Cards/SpaceCardModal.js
  components/Dashboard/Cards/SpacePackage.js
  components/Dashboard/DashboardContainer.js
  components/Dashboard/Sidebar.js
  components/Shared/Card.js
  components/Shared/SpaceCard.js
  data/spaceCardModalTestData.js
  pages/dashboard/index.js
  pages/spaces/study-space-demo.js
  public/images/avatar/anime.png
  public/images/avatar/cartoon.png
  styles/Theme.js
Labels: enhancement, help wanted

#94 84 new typography settings
  package-lock.json
  styles/Theme.js
Labels: enhancement

#96 95 message caching
  components/Spaces/Chat/index.js
  components/Spaces/StudySpace/People.js
  components/Spaces/Video/CallTabs.js
  pages/room/[...id].js
Labels: enhancement

#100 98 call tabs data driven
  components/Auth/Auth.module.css
  components/Auth/AuthDialog.js
  components/Spaces/Chat/index.js
  components/Spaces/Music/index.js
  components/Spaces/StudySpace/People.js
  components/Spaces/Video/CallTabs.js
  jsconfig.json
  pages/_document.js
  pages/room/[...id].js
  utils/dbConnect.js
  utils/renderComponent.js
Labels: improvement

#103 77 update profile settings UI
  components/Dashboard/CollapsableDrawer.js
  components/Dashboard/DashboardContainer.js
  components/Dashboard/Modals/ProfileDialog/AccountDetails.js
  components/Dashboard/Modals/ProfileDialog/ChangePassword.js
  components/Dashboard/Modals/ProfileDialog/index.js
  pages/dashboard/index.js
  styles/Theme.js
Labels: improvement

#108 106 music tab study space
  components/Spaces/Chat/index.js
  components/Spaces/Music/Tabs/OurPicks.js
  components/Spaces/Music/Tabs/Queue/Song.js
  components/Spaces/Music/Tabs/Queue/index.js
  components/Spaces/Music/Tabs/Youtube.js
  components/Spaces/Music/index.js
  components/Spaces/Video/CallTabs/TabPanelHeader.js
  components/Spaces/Video/CallTabs/index.js
  package-lock.json
  package.json
  pages/room/[...id].js
  pages/spaces/study-space-demo.js
  styles/Theme.js
Labels: enhancement

#114 112 start translations
  components/Auth/AuthDialog.js
  components/Landing/Header/index.js
  components/Layout/Meta.js
  components/Layout/index.js
  jsconfig.json
  next-i18next.config.js
  next.config.js
  package-lock.json
  package.json
  pages/_app.js
  pages/_document.js
  pages/api/user/create-new-friend.js
  pages/api/user/create-new-user.js
  pages/api/user/get-user-list.js
  pages/auth/index.js
  pages/dashboard/index.js
  pages/friends/index.js
  pages/landing/index.js
  pages/room/[...id].js
  pages/room/index.js
  pages/spaces/study-space-demo.js
  public/favicon.ico
  public/locales/de/common.json
  public/locales/en/common.json
  public/locales/es/common.json
  public/locales/fr/common.json
  public/locales/ja/common.json
  public/locales/ko/common.json
  public/locales/zh/common.json
  public/vercel.svg
Labels: improvement

#110 [ DRAFT ] add room to backend
  components/Dashboard/Cards/DashboardCard.js
  components/Dashboard/Cards/SpaceCardModal.js
  components/Dashboard/Cards/SpacePackage.js
  components/Dashboard/DashboardContainer.js
  components/Landing/LandingSpaces.js
  components/Shared/SpaceCard.js
  data/spaceCardTestData.js
  models/Spaces.js
  pages/api/auth/[...nextauth].js
  pages/api/profile/update-image.js
  pages/api/profile/update-password.js
  pages/api/profile/update-profile.js
  pages/api/spaces/create-new-space.js
  pages/api/user/get-user.js
  pages/dashboard/index.js
  pages/landing/index.js
  pages/room/index.js
Labels: help wanted

#117 Use Session to get current user when creating new space
  atoms/client.js
  components/Dashboard/Cards/SpaceCardModal.js
  components/Dashboard/Modals/ProfileDialog/AccountDetails.js
  jsconfig.json
  pages/dashboard/index.js
  pages/landing/index.js
  pages/room/index.js
Labels: enhancement
